# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-step-functions
  description: Terraform module to provision AWS Step Functions
  homepage: https://cloudposse.com/accelerate
  topics: ""
